### ISSUE TITLE
在使用vercel部署后使用，报了两个错，麻烦各位大佬帮忙看看。

### ISSUE THREAD

**Issue by me4p0** [Jazee6/cloudflare-ai-web#9]
在使用vercel部署后使用，报了两个错，麻烦各位大佬帮忙看看。
1.首先，因为部署代理的链接不可用，因此采用了修改**nuxt.config.ts**文件的方法，修改后如下，不知是否对不对？

```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    devtools: {enabled: true},
    modules: ['@nuxt/ui'],
    css: ['~/assets/css/style.css'],
    devServer: {
        port: 3001,
    },
    routeRules: {
        '/': {
            prerender: true,
        }
    },
    app: {
        head: {
            title: 'CF AI Web',
            meta: [
                {
                    name: 'keywords',
                    content: 'CF AI Web, AI, Cloudflare Workers, ChatGPT, GeminiPro, Google Generative AI'
                },
                {
                    name: 'description',
                    content: 'Integrated web platform supporting GeminiPro/Cloudflare Workers AI/ChatGPT by Jazee6'
                }
            ]
        }
    }
})

nitro: {
    vercel: {
        regions: ["cle1", "iad1", "pdx1", "sfo1", "sin1", "syd1", "hnd1", "kix1"]
    }
}
```

2.环境变量添加了gemini api key，现在报错代码如下。

```
[POST] /api/auth/gemini/?model=gemini-pro status=500

[nuxt] [request error] [unhandled] [500] [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: [400 Bad Request] User location is not supported for the API use.
  at (index.mjs:1:117483)  
  at (index.mjs:1:121866)

```

**Comment by Jazee6** [comment]
你好，配置需要放在defineNuxtConfig中

**Comment by me4p0** [comment]
像这样？
```
export default defineNuxtConfig({
    devtools: {enabled: true},
    modules: ['@nuxt/ui'],
    css: ['~/assets/css/style.css'],
    devServer: {
        port: 3001,
    },
    routeRules: {
        '/': {
            prerender: true,
        }
    },
    app: {
        head: {
            title: 'CF AI Web',
            meta: [
                {
                    name: 'keywords',
                    content: 'CF AI Web, AI, Cloudflare Workers, ChatGPT, GeminiPro, Google Generative AI'
                },
                {
                    name: 'description',
                    content: 'Integrated web platform supporting GeminiPro/Cloudflare Workers AI/ChatGPT by Jazee6'
                }
            ]
        }
    }
    nitro: {
        vercel: {
            regions: ["cle1", "iad1", "pdx1", "sfo1", "sin1", "syd1", "hnd1", "kix1"]
        }
    }
})
```

**Comment by Jazee6** [comment]
是的，不过前面少了一个`,`

**Comment by me4p0** [comment]
感谢大佬,在上面重新编辑了，方便业余选手复制。

**Comment by me4p0** [comment]
redepoly了下，还是一样的报错，困惑……

**Comment by Jazee6** [comment]
<img width="1002" alt="image" src="https://github.com/Jazee6/cloudflare-ai-web/assets/59408913/e2ef2342-aad5-478c-b6a1-d7397a4df55f">

检查

**Comment by me4p0** [comment]
没有生效，我的上面显示的是global
![image](https://github.com/Jazee6/cloudflare-ai-web/assets/37094697/c6ac0d6f-a3d7-4b8e-89f2-20d7c73493b3)

**Comment by me4p0** [comment]
已解决，可以正常使用了，出现了一个特别noobs的操作，我github仓库里修改来修改去，原来我的仓库是在gitlab里 ，lOL，谢谢
